name: Quality Gate

on: push

permissions:
  contents: read

jobs:
  commitlint:
    name: Enforce conventional commits
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{github.event.ref}}

    - name: Setup Node 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Enforce conventional commits
      run: |
        npm install
        npx commitlint --to ${{github.event.ref}}

  ci:
    name: CI quality checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Cache PlatformIO toolchain
      uses: actions/cache@v3
      with:
        key: platformio-toolchain-cache
        path: /home/runner/.platformio

    - name: Build firmware
      run: |
        pio run --environment nrf52840_dk
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: zephyr-build-output
        path: |
          .pio/build/**/*.config
          .pio/build/**/*.dts
          .pio/build/**/*.elf
